### PR TITLE
fix mixing bracket for sha3 code

### PR DESCRIPTION
**Pull request by petrs**
Fixing bug as reported by @Bart-Janssen in https://github.com/MiragePV/OptimizedJCAlgs/issues/4

### CODE REVIEW

**Review by MiragePV — APPROVED** [review]
Thanks, merging.

I am not actively taking care of this code anymore, feel free to fork it and use it for your convenience ;)

**Comment by petrs** [comment]
Thank you @MiragePV for this merge. If you would not be against, we can move it under lab github org - we started to extend some of the algorithms further, so it would be cleaner to work directly on upstream. If you agree, please add me as maintainer for this repo and I will migrate it under lab org.

**Comment by Bart-Janssen** [comment]
Extend more, is there a plan to include Shake to this smart card code?

**Comment by petrs** [comment]
@Bart-Janssen We did not considered SHAKE so far, however after a quick look at its structure, it shall be doable given Keccak is already there. Can you please open issue with SHAKE request please? (however, if you are in hurry for that code, then best would be to tweak existing code yourself and maybe ope PR)

**Comment by Bart-Janssen** [comment]
Yeah I was planning to add it (at least to my own code), I will try this tomorrow and I can share this with here if this is wanted.

**Comment by MiragePV** [comment]
> Thank you @MiragePV for this merge. If you would not be against, we can move it under lab github org - we started to extend some of the algorithms further, so it would be cleaner to work directly on upstream. If you agree, please add me as maintainer for this repo and I will migrate it under lab org.

Sure, no problem. I sent you an invite for collaborator role. Feel free to use any of it.
I have fond memories of my time at CRoCS and working with you, I am happy that this work is still going forward and hopefully some new students will benefit from this project.

**Comment by petrs** [comment]
Thank you @MiragePV - that is what we plan to do - was pleasure to work with you :). Can you pls set my access rights to owner so I can move repository under new org (current push rights are not enough for that)

**Comment by Bart-Janssen** [comment]
> > Thank you @MiragePV for this merge. If you would not be against, we can move it under lab github org - we started to extend some of the algorithms further, so it would be cleaner to work directly on upstream. If you agree, please add me as maintainer for this repo and I will migrate it under lab org.
> 
> Sure, no problem. I sent you an invite for collaborator role. Feel free to use any of it. I have fond memories of my time at CRoCS and working with you, I am happy that this work is still going forward and hopefully some new students will benefit from this project.

As being a student, yeah I will :)

**Comment by MiragePV** [comment]
> Thank you @MiragePV - that is what we plan to do - was pleasure to work with you :). Can you pls set my access rights to owner so I can move repository under new org (current push rights are not enough for that)

Ahoj, prehodil som repo do organizacie, lebo ako personal repo som ti nevedel pridelit dostatocne prava. Mas admina, takze hadam s repom uz mozes robit cokolvek, co potrebujete :)

**Comment by Bart-Janssen** [comment]
I have added Shake128 and Shake256, however when I create a new branch with the added code and push it, it says I do not have the correct rights.

**Comment by petrs** [comment]
@Bart-Janssen very good, thank you. The addition needs to be done via Pull Request - fork this repo, add code on your side, then open PR against this repository. Please try that - if anything will not work, I will help you

**Pull request merged**
